package com.example.demo.exceptions;

public class ChamadoNaoEncontradoException extends RuntimeException {
    public ChamadoNaoEncontradoException(Integer id) {
        super("Chamado com o ID " + id + " n√£o foi encontrado.");
    }
}